"""init 24 tables

Revision ID: 01f334d41c86
Revises: 
Create Date: 2026-08-18 15:21:00.772791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '01f334d41c86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('prev_event_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    op.create_table('benchmark_cases',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('nl_requirement', sa.Text(), nullable=False),
    sa.Column('expected_schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_risk_level', sa.String(length=4), nullable=False),
    sa.Column('is_malicious', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_cases_version'), 'benchmark_cases', ['version'], unique=False)
    op.create_table('benchmark_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('suite_version', sa.String(length=32), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capability_tokens',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('tool_intent', sa.String(length=64), nullable=False),
    sa.Column('artifact_digest', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce'),
    sa.UniqueConstraint('token_digest')
    )
    op.create_table('keyring',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('public_key_b64', sa.String(length=128), nullable=False),
    sa.Column('encrypted_private_key', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('aggregate_type', sa.String(length=32), nullable=False),
    sa.Column('aggregate_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('connections',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('conn_type', sa.String(length=32), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("conn_type in ('mysql','postgresql','oracle','doris','clickhouse','s3','rest_api')"),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index(op.f('ix_connections_conn_type'), 'connections', ['conn_type'], unique=False)
    op.create_table('evolution_candidates',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('review_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evolution_candidates_project_id'), 'evolution_candidates', ['project_id'], unique=False)
    op.create_index(op.f('ix_evolution_candidates_status'), 'evolution_candidates', ['status'], unique=False)
    op.create_table('file_assets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_file_assets_project_id'), 'file_assets', ['project_id'], unique=False)
    op.create_table('gray_flags',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('flag_key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'flag_key')
    )
    op.create_table('pipelines',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code')
    )
    op.create_table('project_memberships',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('admin','engineer','approver_data','approver_security','operator','auditor')"),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', 'role')
    )
    op.create_table('project_role_grants',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_slot', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role_slot in ('maker','checker1','checker2','operator')"),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', 'role_slot')
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_digest')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('metadata_profiles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('connection_id', sa.BigInteger(), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('masked_sample_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_profiles_connection_id'), 'metadata_profiles', ['connection_id'], unique=False)
    op.create_index(op.f('ix_metadata_profiles_object_name'), 'metadata_profiles', ['object_name'], unique=False)
    op.create_table('pipeline_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pipeline_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('etl_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hocon_text', sa.Text(), nullable=False),
    sa.Column('artifact_digest', sa.String(length=64), nullable=False),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('gate_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_digest'),
    sa.UniqueConstraint('pipeline_id', 'version_number')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pending_question_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['pipeline_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_table('pipeline_artifacts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('artifact_digest', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['pipeline_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_artifacts_version_id'), 'pipeline_artifacts', ['version_id'], unique=False)
    op.create_table('preparations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('maker_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('resource_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('impact_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_classification', sa.String(length=16), nullable=False),
    sa.Column('budget_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rollback_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_level', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['maker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['pipeline_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preparations_status'), 'preparations', ['status'], unique=False)
    op.create_index(op.f('ix_preparations_version_id'), 'preparations', ['version_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('preparation_id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('required_role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('approver_id', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['preparation_id'], ['preparations.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['pipeline_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preparation_id', 'required_role')
    )
    op.create_table('execution_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('preparation_id', sa.BigInteger(), nullable=True),
    sa.Column('run_kind', sa.String(length=16), nullable=False),
    sa.Column('capability_token_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('sub_stage', sa.String(length=16), nullable=True),
    sa.Column('engine_job_id', sa.String(length=128), nullable=True),
    sa.Column('input_records', sa.BigInteger(), nullable=True),
    sa.Column('output_records', sa.BigInteger(), nullable=True),
    sa.Column('error_records', sa.BigInteger(), nullable=True),
    sa.Column('bytes_processed', sa.BigInteger(), nullable=True),
    sa.Column('source_row_count', sa.BigInteger(), nullable=True),
    sa.Column('row_count_check', sa.String(length=16), nullable=True),
    sa.Column('diagnosis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(run_kind = 'execute' AND preparation_id IS NOT NULL) OR (run_kind = 'dry_run' AND preparation_id IS NULL)"),
    sa.ForeignKeyConstraint(['preparation_id'], ['preparations.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['pipeline_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_runs_preparation_id'), 'execution_runs', ['preparation_id'], unique=False)
    op.create_index(op.f('ix_execution_runs_status'), 'execution_runs', ['status'], unique=False)
    op.create_index(op.f('ix_execution_runs_version_id'), 'execution_runs', ['version_id'], unique=False)
    op.create_index('ix_execution_runs_version_status', 'execution_runs', ['version_id', 'status'], unique=False)
    op.create_table('runtime_supervision_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('execution_run_id', sa.BigInteger(), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('action_taken', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_run_id'], ['execution_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_supervision_snapshots_execution_run_id'), 'runtime_supervision_snapshots', ['execution_run_id'], unique=False)
    # ### end Alembic commands ###

    # ── 只追加 / 冻结触发器（DATA 5.3，逐条执行：asyncpg 一次只收一条语句）──
    op.execute("CREATE OR REPLACE FUNCTION audit_events_append_only() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'audit_events 只允许追加'; END $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER trg_audit_events_append_only BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION audit_events_append_only()")
    op.execute("CREATE OR REPLACE FUNCTION append_only() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION '表 % 只允许追加', TG_TABLE_NAME; END $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER trg_metadata_profiles_append_only BEFORE UPDATE OR DELETE ON metadata_profiles FOR EACH ROW EXECUTE FUNCTION append_only()")
    op.execute("CREATE TRIGGER trg_snapshots_append_only BEFORE UPDATE OR DELETE ON runtime_supervision_snapshots FOR EACH ROW EXECUTE FUNCTION append_only()")
    # capability_tokens：UPDATE 仅允许置位 consumed_at，DELETE 禁止（Replay Guard 例外）
    op.execute("CREATE OR REPLACE FUNCTION capability_tokens_limited_update() RETURNS trigger AS $$ BEGIN IF NEW.id != OLD.id OR NEW.consumed_at IS NOT DISTINCT FROM OLD.consumed_at THEN RAISE EXCEPTION 'capability_tokens 仅允许置位 consumed_at'; END IF; RETURN NEW; END $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER trg_capability_tokens_limited_update BEFORE UPDATE ON capability_tokens FOR EACH ROW EXECUTE FUNCTION capability_tokens_limited_update()")
    op.execute("CREATE TRIGGER trg_capability_tokens_no_delete BEFORE DELETE ON capability_tokens FOR EACH ROW EXECUTE FUNCTION append_only()")
    # pipeline_versions：is_immutable=true 后禁止 UPDATE/DELETE
    op.execute("CREATE OR REPLACE FUNCTION pipeline_versions_frozen() RETURNS trigger AS $$ BEGIN IF OLD.is_immutable THEN RAISE EXCEPTION '版本已冻结（is_immutable），禁止修改或删除'; END IF; RETURN NEW; END $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER trg_pipeline_versions_frozen BEFORE UPDATE OR DELETE ON pipeline_versions FOR EACH ROW EXECUTE FUNCTION pipeline_versions_frozen()")
    # preparations：冻结后仅允许 status/updated_at 变更
    op.execute("CREATE OR REPLACE FUNCTION preparations_status_only() RETURNS trigger AS $$ BEGIN IF NEW.input_fingerprint IS DISTINCT FROM OLD.input_fingerprint OR NEW.risk_level IS DISTINCT FROM OLD.risk_level OR NEW.maker_id IS DISTINCT FROM OLD.maker_id OR NEW.budget_json::text IS DISTINCT FROM OLD.budget_json::text OR NEW.version_id != OLD.version_id THEN RAISE EXCEPTION '准备单已冻结，仅允许 status 变更'; END IF; RETURN NEW; END $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER trg_preparations_status_only BEFORE UPDATE ON preparations FOR EACH ROW EXECUTE FUNCTION preparations_status_only()")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runtime_supervision_snapshots_execution_run_id'), table_name='runtime_supervision_snapshots')
    op.drop_table('runtime_supervision_snapshots')
    op.drop_index('ix_execution_runs_version_status', table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_version_id'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_status'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_preparation_id'), table_name='execution_runs')
    op.drop_table('execution_runs')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_preparations_version_id'), table_name='preparations')
    op.drop_index(op.f('ix_preparations_status'), table_name='preparations')
    op.drop_table('preparations')
    op.drop_index(op.f('ix_pipeline_artifacts_version_id'), table_name='pipeline_artifacts')
    op.drop_table('pipeline_artifacts')
    op.drop_table('agent_runs')
    op.drop_table('pipeline_versions')
    op.drop_index(op.f('ix_metadata_profiles_object_name'), table_name='metadata_profiles')
    op.drop_index(op.f('ix_metadata_profiles_connection_id'), table_name='metadata_profiles')
    op.drop_table('metadata_profiles')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('project_role_grants')
    op.drop_table('project_memberships')
    op.drop_table('pipelines')
    op.drop_table('gray_flags')
    op.drop_index(op.f('ix_file_assets_project_id'), table_name='file_assets')
    op.drop_table('file_assets')
    op.drop_index(op.f('ix_evolution_candidates_status'), table_name='evolution_candidates')
    op.drop_index(op.f('ix_evolution_candidates_project_id'), table_name='evolution_candidates')
    op.drop_table('evolution_candidates')
    op.drop_index(op.f('ix_connections_conn_type'), table_name='connections')
    op.drop_table('connections')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_table('keyring')
    op.drop_table('capability_tokens')
    op.drop_table('benchmark_runs')
    op.drop_index(op.f('ix_benchmark_cases_version'), table_name='benchmark_cases')
    op.drop_table('benchmark_cases')
    op.drop_index(op.f('ix_audit_events_project_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
